# Generated by Django 2.1.7 on 2019-03-05 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email_address')),
                ('token_id', models.CharField(max_length=40)),
                ('token_expires', models.DateTimeField(default=datetime.datetime(2019, 3, 5, 22, 18, 34, 69576))),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
