# Generated by Django 2.1.7 on 2019-03-06 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190306_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='token_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
